spring.application.name=Sereneflows
youtube.api.key=AIzaSyAtTS41SNt5_eYi7GoE2T_tGyf3U-fncTE
spotify.client.id=deda6fdfb69a487f9bb5198d111094c3
spotify.client.secret=ffab6ad6db6b4c63ac73a1656c4354a6
spotify.redirect.uri=http://127.0.0.1:8080/callback